version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:80
    container_name: ima-coco_nginx
    tty: true
    volumes:
      - ./nginx/public:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/error/:/var/log/nginx/
    # environment:
    #   VIRTUAL_HOST: 'ima-coco'
    depends_on:
      - api
      - front

  # Debian
  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    container_name: ima-coco_api
    tty: true
    volumes:
      - ./api:/usr/src/app
    command: bash -c "yarn install && yarn dev"
    ports:
      - ${API_PORT}:3000
  
  # Debian
  front:
    build:
      context: ./docker/front
      dockerfile: Dockerfile
    container_name: ima-coco_front
    tty: true
    volumes: 
      - ./front:/usr/src/app
    command: bash -c "yarn install && yarn dev"
    ports: 
      - ${FRONT_PORT}:3000
    environment: 
      - NODE_ENV=${NODE_ENV}
  
  db:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    depends_on:
      - db

# networks:
#   default:
#     external:
#       name: nginx-proxy-network